import type { Exercise } from '../domain/exercise';

/**
 * Catálogo estendido derivado do dataset aberto
 * https://github.com/hasaneyldrm/exercises-dataset — nomes e instruções
 * adaptados para o português do Brasil.
 *
 * As animações pertencem à Gym visual e só podem ser exibidas com a
 * atribuição abaixo visível ao lado da mídia.
 */
export const EXERCISE_MEDIA_ATTRIBUTION = '© Gym visual — gymvisual.com';

export const EXTENDED_EXERCISE_CATALOG: readonly Exercise[] = [
  {
    id: 'barbell-front-squat',
    name: 'Agachamento Frontal com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Apoie a barra na frente dos ombros, pés na largura dos ombros e pontas levemente para fora. Desça empurrando o quadril para trás, mantendo o tronco ereto, e suba estendendo pernas.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0042-zG0zs85.gif',
  },
  {
    id: 'barbell-full-squat',
    name: 'Agachamento Livre Completo',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Apoie a barra no trapézio, pés na largura dos ombros. Agache até abaixo da linha dos joelhos mantendo core firme e peito aberto, depois suba empurrando o chão com os pés.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0043-qXTaZnJ.gif',
  },
  {
    id: 'barbell-romanian-deadlift',
    name: 'Levantamento Terra Romeno',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'barbell',
    instructions: 'Segure a barra em pronação com joelhos semiflexionados. Desça a barra rente às pernas fazendo a dobradiça de quadril e mantendo a coluna neutra; suba contraindo glúteos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0085-wQ2c4XD.gif',
  },
  {
    id: 'barbell-sumo-deadlift',
    name: 'Levantamento Terra Sumô',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps', 'back'],
    equipment: 'barbell',
    instructions: 'Posicione os pés bem afastados com pontas para fora e a barra centralizada. Pegue a barra em pronação, peito alto, e estenda quadris e joelhos para levantar o peso.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0117-KgI0tqW.gif',
  },
  {
    id: 'barbell-close-grip-bench-press',
    name: 'Supino Fechado com Barra',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'barbell',
    instructions: 'Deitado no banco, segure a barra com pegada mais estreita que os ombros. Desça controlando até o peito com os cotovelos próximos ao corpo e empurre até estender os braços.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0030-J6Dx1Mu.gif',
  },
  {
    id: 'barbell-lying-triceps-extension-skull-crusher',
    name: 'Tríceps Testa com Barra',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'barbell',
    instructions: 'Deitado no banco, mantenha os braços estendidos acima do peito. Flexione apenas os cotovelos levando a barra até a testa e estenda os braços contraindo o tríceps.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0060-h8LFzo9.gif',
  },
  {
    id: 'barbell-rack-pull',
    name: 'Rack Pull com Barra',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'barbell',
    instructions: 'Ajuste a barra na altura dos joelhos no rack. Pegue em pronação, peito alto, e estenda quadris e joelhos até ficar ereto; desça controlando com a coluna neutra.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0074-za9Ni4z.gif',
  },
  {
    id: 'barbell-hack-squat',
    name: 'Agachamento Hack com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Segure a barra atrás das pernas com os pés na largura dos ombros. Agache flexionando joelhos e quadris, mantendo a coluna neutra, e suba estendendo as pernas.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0046-5VCj6iH.gif',
  },
  {
    id: 'barbell-seated-overhead-press',
    name: 'Desenvolvimento Sentado com Barra',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'back'],
    equipment: 'barbell',
    instructions: 'Sentado com a coluna apoiada, segure a barra na altura dos ombros em pronação. Empurre acima da cabeça até estender os braços e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0091-kTbSH9h.gif',
  },
  {
    id: 'barbell-standing-wide-military-press',
    name: 'Desenvolvimento Militar Pegada Larga',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'back'],
    equipment: 'barbell',
    instructions: 'Em pé, segure a barra em pronação um pouco mais larga que os ombros, na altura dos ombros. Empurre acima da cabeça sem arquear a lombar e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1457-Kyd9Rz5.gif',
  },
  {
    id: 'barbell-rear-delt-row',
    name: 'Remada Alta Curvada para Posterior',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'barbell',
    instructions: 'Inclinado à frente com coluna neutra, segure a barra em pronação. Puxe abrindo os cotovelos na linha dos ombros, contraindo o deltoide posterior, e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0076-S9zHIvU.gif',
  },
  {
    id: 'barbell-glute-bridge',
    name: 'Elevação de Quadril com Barra',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'barbell',
    instructions: 'Deitado de costas, joelhos flexionados e barra sobre o quadril. Eleve o quadril até alinhar joelhos e ombros contraindo os glúteos e desça sem encostar totalmente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1409-qKBpF7I.gif',
  },
  {
    id: 'barbell-one-arm-bent-over-row',
    name: 'Remada Unilateral com Barra',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'barbell',
    instructions: 'Com tronco inclinado e coluna neutra, segure a barra com uma das mãos em pronação. Puxe até o tronco com o cotovelo junto ao corpo e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0064-Jsgsc27.gif',
  },
  {
    id: 'barbell-incline-bench-press',
    name: 'Supino Inclinado com Barra',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    instructions: 'Ajuste o banco inclinado e segure a barra um pouco mais larga que os ombros. Desça até a parte alta do peito e empurre até estender os braços, sem travar os cotovelos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0047-3TZduzM.gif',
  },
  {
    id: 'barbell-deadlift',
    name: 'Levantamento Terra com Barra',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'barbell',
    instructions: 'Pés na largura dos ombros e barra junto às canelas. Pegue em pronação, peito alto, e levante empurrando o chão enquanto estende quadris e joelhos ao mesmo tempo.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0032-ila4NZS.gif',
  },
  {
    id: 'barbell-shrug',
    name: 'Encolhimento de Ombros com Barra',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'barbell',
    instructions: 'Em pé, segure a barra à frente do corpo em pronação com os braços estendidos. Eleve os ombros em direção às orelhas contraindo o trapézio e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0095-dG7tG5y.gif',
  },
  {
    id: 'cable-lat-pulldown-full-range-of-motion',
    name: 'Puxada Frontal na Polia Amplitude Total',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    instructions: 'Sente na puxada com os joelhos travados sob os apoios e pegada pronada aberta. Puxe a barra até a altura do peito e retorne controlando até estender totalmente os braços.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2330-LEprlgG.gif',
  },
  {
    id: 'cable-pulldown',
    name: 'Puxada na Polia Alta',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    instructions: 'Sente com o tronco ereto e pegada pronada um pouco além da largura dos ombros. Puxe a barra até a parte alta do peito, juntando as escápulas, e suba controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0198-RVwzP10.gif',
  },
  {
    id: 'cable-seated-row',
    name: 'Remada Sentada na Polia',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    instructions: 'Sente com os pés apoiados e joelhos levemente flexionados. Puxe o triângulo em direção ao abdômen, aproximando as escápulas, e volte sem arredondar a coluna.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0861-fUBheHs.gif',
  },
  {
    id: 'cable-triceps-pushdown-v-bar',
    name: 'Tríceps Pulley com Barra V',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Segure a barra V com pegada pronada e mantenha os cotovelos fixos ao lado do tronco. Estenda os cotovelos até travar os braços e retorne devagar até 90 graus.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0241-gAwDzB3.gif',
  },
  {
    id: 'cable-standing-rear-delt-row-with-rope',
    name: 'Remada Alta Posterior na Polia com Corda',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'cable',
    instructions: 'Em pé, segure a corda na polia na altura do rosto com os braços estendidos. Puxe abrindo os cotovelos acima da linha dos ombros e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0233-ZfyAGhK.gif',
  },
  {
    id: 'cable-standing-fly',
    name: 'Crucifixo na Polia em Pé',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Com as polias na altura do peito, dê um passo à frente e mantenha leve flexão de cotovelos. Junte as mãos à frente do peito e abra devagar até sentir o alongamento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0227-Pr9Rhf4.gif',
  },
  {
    id: 'cable-upper-chest-crossovers',
    name: 'Crossover Alto para Peitoral Superior',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Com as polias baixas, segure as manoplas e mantenha uma perna à frente. Cruze as mãos para cima e à frente na altura dos ombros e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1270-j7XMAyn.gif',
  },
  {
    id: 'cable-kneeling-crunch',
    name: 'Abdominal Ajoelhado na Polia',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'cable',
    instructions: 'Ajoelhe de costas para a polia alta com a corda ao lado da cabeça. Flexione a coluna aproximando os cotovelos das coxas usando o abdômen e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0175-WW95auq.gif',
  },
  {
    id: 'cable-straight-arm-pulldown',
    name: 'Pullover na Polia Alta',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders', 'biceps'],
    equipment: 'cable',
    instructions: 'Em pé de frente para a polia, segure a barra com braços estendidos. Puxe a barra até as coxas contraindo o dorsal e retorne controlando sem dobrar os cotovelos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0238-x69MAlq.gif',
  },
  {
    id: 'cable-pull-through-with-rope',
    name: 'Pull Through na Polia com Corda',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'cable',
    instructions: 'De costas para a polia baixa, passe a corda entre as pernas e afaste-se. Empurre o quadril para trás com a coluna neutra e volte contraindo os glúteos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0196-OM46QHm.gif',
  },
  {
    id: 'cable-one-arm-curl',
    name: 'Rosca Unilateral na Polia',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Em pé de frente para a polia baixa, segure a manopla com pegada supinada. Flexione o cotovelo mantendo-o junto ao corpo e desça controlando até estender o braço.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0190-YTur5nR.gif',
  },
  {
    id: 'cable-lateral-raise-goj6ezq',
    name: 'Elevação Lateral na Polia',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'triceps'],
    equipment: 'cable',
    instructions: 'Em pé ao lado da polia baixa, segure a manopla com o braço quase estendido. Eleve o braço lateralmente até a altura do ombro e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0178-goJ6ezq.gif',
  },
  {
    id: 'cable-shoulder-press',
    name: 'Desenvolvimento na Polia',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'back'],
    equipment: 'cable',
    instructions: 'Com as manoplas na altura dos ombros e cotovelos flexionados, empurre para cima até quase estender os braços. Desça controlando até os cotovelos a 90 graus.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0219-PzQanLE.gif',
  },
  {
    id: 'cable-kickback',
    name: 'Tríceps Coice na Polia',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    instructions: 'Incline o tronco à frente com a coluna neutra e o cotovelo elevado junto ao corpo. Estenda o cotovelo para trás até travar o braço e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0860-HEJ6DIX.gif',
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Levantamento Terra Romeno com Halteres',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'back'],
    equipment: 'dumbbell',
    instructions: 'Em pé, com halteres à frente das coxas, empurre o quadril para trás e desça os pesos rente às pernas. Suba contraindo glúteos e posteriores com a coluna neutra.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1459-rR0LJzx.gif',
  },
  {
    id: 'dumbbell-front-raise',
    name: 'Elevação Frontal com Halteres',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['biceps', 'back'],
    equipment: 'dumbbell',
    instructions: 'Em pé, halteres à frente das coxas com pegada pronada. Eleve os braços estendidos até a altura dos ombros, pause e desça devagar até a posição inicial.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0310-3eGE2JC.gif',
  },
  {
    id: 'dumbbell-arnold-press',
    name: 'Desenvolvimento Arnold com Halteres',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    instructions: 'Sentado com as costas apoiadas, segure os halteres na altura dos ombros com as palmas voltadas para você. Empurre para cima girando os punhos até as palmas ficarem à frente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2137-Xy4jlWA.gif',
  },
  {
    id: 'dumbbell-concentration-curl',
    name: 'Rosca Concentrada com Halter',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    instructions: 'Sentado no banco, apoie o cotovelo na parte interna da coxa com o braço estendido. Flexione o cotovelo levando o halter até o ombro, contraindo o bíceps, e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0297-gvsWLQw.gif',
  },
  {
    id: 'dumbbell-preacher-curl',
    name: 'Rosca Scott com Halteres',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    instructions: 'Apoie os braços no banco Scott com o peito encostado e os halteres em supinação, braços estendidos. Flexione os cotovelos contraindo o bíceps e retorne devagar sem perder o apoio.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0372-jivWf8n.gif',
  },
  {
    id: 'dumbbell-upright-row',
    name: 'Remada Alta com Halteres',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'dumbbell',
    instructions: 'Em pé, pés na largura dos ombros, segure os halteres em pronação à frente das coxas. Puxe os pesos até a altura do queixo liderando com os cotovelos e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0437-ainizkb.gif',
  },
  {
    id: 'dumbbell-side-bend',
    name: 'Flexão Lateral de Tronco com Halter',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'dumbbell',
    instructions: 'Em pé, segure um halter ao lado do corpo com o core ativado. Incline o tronco lateralmente descendo o peso o máximo confortável, pause e volte à posição inicial sem rotacionar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0407-IpONWYv.gif',
  },
  {
    id: 'dumbbell-one-arm-shoulder-press',
    name: 'Desenvolvimento Unilateral com Halter',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'back'],
    equipment: 'dumbbell',
    instructions: 'Em pé, com um halter na altura do ombro e palma à frente, empurre até estender o braço acima da cabeça. Pause no topo e desça devagar mantendo o core firme.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0361-84RyJf8.gif',
  },
  {
    id: 'dumbbell-rear-delt-raise',
    name: 'Crucifixo Inverso com Halteres',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    instructions: 'Com joelhos semiflexionados, incline o tronco à frente mantendo a coluna neutra. Eleve os halteres lateralmente com leve flexão de cotovelos até a linha dos ombros e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2292-mu5Guxt.gif',
  },
  {
    id: 'dumbbell-lying-triceps-extension',
    name: 'Tríceps Testa com Halteres',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deitado no banco, estenda os halteres acima do peito com as palmas frente a frente. Flexione os cotovelos levando os pesos até a testa e estenda os braços contraindo o tríceps.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0351-mpKZGWz.gif',
  },
  {
    id: 'dumbbell-bent-over-row',
    name: 'Remada Curvada com Halteres',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    instructions: 'Com joelhos semiflexionados, incline o tronco à frente mantendo a coluna reta e os halteres pendendo. Puxe os pesos até a lateral do tronco e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0293-BJ0Hz5L.gif',
  },
  {
    id: 'dumbbell-goblet-squat',
    name: 'Agachamento Goblet com Halter',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Segure o halter na vertical junto ao peito, pés na largura dos ombros. Desça jogando o quadril para trás até as coxas ficarem paralelas ao chão e suba empurrando pelos calcanhares.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1760-yn8yg1r.gif',
  },
  {
    id: 'dumbbell-lunge',
    name: 'Afundo com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Em pé com um halter em cada mão, dê um passo à frente e desça até o joelho de trás quase tocar o chão. Mantenha o tronco ereto e retorne empurrando o calcanhar da frente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0336-RRWFUcw.gif',
  },
  {
    id: 'dumbbell-step-up',
    name: 'Subida no Banco com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'De frente para o banco, segure os halteres ao lado do corpo. Apoie todo o pé no banco, suba empurrando pelo calcanhar até estender a perna e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0431-aXtJhlg.gif',
  },
  {
    id: 'dumbbell-seated-calf-raise',
    name: 'Panturrilha Sentado com Halter',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'dumbbell',
    instructions: 'Sentado, apoie o halter sobre as coxas e posicione a ponta dos pés em um step, com os calcanhares livres. Eleve os calcanhares ao máximo, contraia e desça alongando a panturrilha.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1379-r29jP7S.gif',
  },
  {
    id: 'dumbbell-fly',
    name: 'Crucifixo com Halteres',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deitado no banco, estenda os halteres acima do peito com leve flexão de cotovelos. Abra os braços em arco até sentir o alongamento no peitoral e retorne contraindo o peito.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0308-yz9nUhF.gif',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Pullover com Halter',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['back', 'triceps'],
    equipment: 'dumbbell',
    instructions: 'Deitado no banco com os pés no chão, segure um halter com as duas mãos acima do peito. Leve o peso para trás da cabeça até alongar o peitoral e retorne controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0375-9XjtHvS.gif',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Supino Reto com Halteres',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deitado no banco com os pés apoiados, estenda os halteres acima do peito. Desça os pesos até a lateral do tórax com cotovelos a 90 graus e empurre de volta ao topo.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0289-SpYC0Kp.gif',
  },
  {
    id: 'lever-seated-calf-raise',
    name: 'Panturrilha Sentado na Máquina',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'machine',
    instructions: 'Sente com os joelhos sob o apoio e a ponta dos pés na plataforma, calcanhares livres. Eleve os calcanhares ao máximo, segure a contração e desça alongando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0594-bOOdeyc.gif',
  },
  {
    id: 'lever-seated-row',
    name: 'Remada Sentada na Máquina',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'machine',
    instructions: 'Sente com o peito apoiado no encosto e pegue as manoplas em pronação. Puxe os cotovelos para trás aproximando as escápulas e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1350-7I6LNUG.gif',
  },
  {
    id: 'lever-chest-press',
    name: 'Supino Reto na Máquina',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas e segure as manoplas na linha do peito. Empurre à frente até estender os braços, expirando, e retorne devagar sem bater os pesos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0576-DOoWcnA.gif',
  },
  {
    id: 'lever-back-extension',
    name: 'Extensão Lombar na Máquina',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    instructions: 'Sente com as costas no apoio e os pés travados, segurando as pegadas. Estenda o tronco para trás contraindo lombar e abdômen, e volte de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0573-rUXfn3R.gif',
  },
  {
    id: 'lever-seated-crunch',
    name: 'Abdominal na Máquina',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'machine',
    instructions: 'Sente com as costas no apoio, segure as manoplas e contraia o abdômen. Flexione o tronco à frente enquanto expira e retorne lentamente sem relaxar o core.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1452-Wgaz7pm.gif',
  },
  {
    id: 'lever-alternate-leg-press',
    name: 'Leg Press Unilateral na Máquina',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'machine',
    instructions: 'Sente com as costas no encosto e apoie um pé na plataforma. Empurre estendendo o joelho sem travá-lo, retorne controlando e depois troque de perna.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2287-V07qpXy.gif',
  },
  {
    id: 'lever-shoulder-press',
    name: 'Desenvolvimento na Máquina',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'chest'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas e segure as manoplas na altura dos ombros. Empurre para cima até quase estender os cotovelos e desça devagar até a posição inicial.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0603-67n3r98.gif',
  },
  {
    id: 'lever-military-press',
    name: 'Desenvolvimento Militar na Máquina',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    instructions: 'Sente ereto com as costas no encosto e pegada um pouco mais aberta que os ombros. Empurre as manoplas acima da cabeça sem travar os cotovelos e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0587-CggQhII.gif',
  },
  {
    id: 'lever-lateral-raise',
    name: 'Elevação Lateral na Máquina',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: 'machine',
    instructions: 'Sente com o tronco apoiado e os braços levemente estendidos nas manoplas. Eleve os braços lateralmente até a altura dos ombros e desça lentamente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0584-dRTfGZT.gif',
  },
  {
    id: 'lever-t-bar-row',
    name: 'Remada Cavalinho na Máquina',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'machine',
    instructions: 'Apoie o peito no suporte e segure as manoplas em pronação, um pouco mais abertas que os ombros. Puxe aproximando as escápulas e retorne alongando as costas.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0606-aaXr7ld.gif',
  },
  {
    id: 'lever-high-row',
    name: 'Remada Alta na Máquina',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    instructions: 'Sente com o peito no apoio e pegue as manoplas altas em pronação. Puxe os cotovelos para baixo e para trás contraindo o dorsal, e retorne de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0581-nZZZy9m.gif',
  },
  {
    id: 'lever-pullover',
    name: 'Pullover na Máquina',
    primaryMuscles: ['back'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas e segure as manoplas com os braços levemente flexionados. Puxe os braços para baixo à frente do corpo contraindo o dorsal e volte devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2285-4U7iLb5.gif',
  },
  {
    id: 'lever-preacher-curl',
    name: 'Rosca Scott na Máquina',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'machine',
    instructions: 'Apoie os braços no banco inclinado e segure as manoplas em supinação. Flexione os cotovelos contraindo o bíceps e desça lentamente até quase estender.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0592-b6hQYMb.gif',
  },
  {
    id: 'lever-bicep-curl',
    name: 'Rosca Direta na Máquina',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas e segure as manoplas em supinação, cotovelos junto ao corpo. Flexione os cotovelos contraindo o bíceps e retorne controlando a descida.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0575-q6y3OhV.gif',
  },
  {
    id: 'lever-seated-dip',
    name: 'Mergulho Sentado na Máquina',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'machine',
    instructions: 'Sente com os pés no chão e segure as manoplas com as palmas para baixo, braços estendidos. Empurre para baixo estendendo os cotovelos e retorne lentamente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1451-BRImeP8.gif',
  },
  {
    id: 'lever-triceps-extension',
    name: 'Tríceps na Máquina',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    instructions: 'Ajuste o banco e apoie as costas no encosto. Segure as pegadas e estenda os cotovelos à frente, mantendo os braços parados; retorne devagar controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0607-Ser9eQp.gif',
  },
  {
    id: 'lever-calf-press',
    name: 'Panturrilha na Máquina Sentado',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings'],
    equipment: 'machine',
    instructions: 'Ajuste o assento e apoie a ponta dos pés na plataforma, com os calcanhares livres. Empurre estendendo os tornozelos ao máximo e desça alongando a panturrilha.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2289-7B4F5nZ.gif',
  },
  {
    id: 'smith-leg-press',
    name: 'Leg Press no Smith',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'machine',
    instructions: 'Apoie as costas no encosto e posicione os pés na plataforma na largura dos ombros. Empurre estendendo os joelhos sem travá-los e retorne controlando até 90 graus.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0760-7zdxRTl.gif',
  },
  {
    id: 'smith-bench-press',
    name: 'Supino Reto no Smith',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    instructions: 'Deite no banco com os pés firmes no chão e pegada pronada um pouco mais aberta que os ombros. Desça a barra até o peito e empurre até estender os cotovelos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0748-trqKQv2.gif',
  },
  {
    id: 'smith-squat',
    name: 'Agachamento no Smith',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'machine',
    instructions: 'Apoie a barra no trapézio, pés na largura dos ombros e pontas levemente para fora. Agache até as coxas ficarem paralelas ao chão e suba empurrando pelos calcanhares.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0770-jFtipLl.gif',
  },
  {
    id: 'smith-deadlift',
    name: 'Levantamento Terra no Smith',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps', 'back'],
    equipment: 'machine',
    instructions: 'Com a barra na altura do quadril, pegada pronada e pés na largura dos ombros, flexione quadril e joelhos mantendo a coluna neutra. Suba estendendo o quadril.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0752-UfePqpx.gif',
  },
  {
    id: 'smith-shrug',
    name: 'Encolhimento no Smith',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    instructions: 'Em pé, pegada pronada e joelhos semiflexionados, mantenha os braços estendidos. Eleve os ombros em direção às orelhas, segure 1 segundo e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0767-OUQ0ZyW.gif',
  },
  {
    id: 'smith-upright-row',
    name: 'Remada Alta no Smith',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'machine',
    instructions: 'Em pé de frente para a máquina, segure a barra com pegada pronada. Puxe a barra rente ao corpo até a altura do peito, cotovelos acima dos punhos, e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0775-1DN3iz4.gif',
  },
  {
    id: 'smith-rear-delt-row',
    name: 'Remada Posterior no Smith',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'machine',
    instructions: 'Incline o tronco à frente com a coluna neutra e pegada pronada aberta. Puxe a barra em direção ao peito abrindo os cotovelos e junte as escápulas; retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0762-nFUwqG6.gif',
  },
  {
    id: 'smith-close-grip-bench-press',
    name: 'Supino Fechado no Smith',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'machine',
    instructions: 'Deite no banco com pegada pronada mais fechada que os ombros. Desça a barra até o peito mantendo os cotovelos junto ao corpo e empurre estendendo os tríceps.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0751-WcHl7ru.gif',
  },
  {
    id: 'push-up-i4hdwkc',
    name: 'Flexão de Braço',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    equipment: 'bodyweight',
    instructions: 'Na posição de prancha, mãos pouco mais abertas que os ombros e corpo alinhado. Desça o peito até perto do chão flexionando os cotovelos e empurre de volta.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0662-I4hDWkc.gif',
  },
  {
    id: 'chest-dip',
    name: 'Mergulho nas Paralelas',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    instructions: 'Apoie-se nas paralelas com braços estendidos e tronco levemente inclinado à frente. Desça flexionando os cotovelos até sentir o peitoral alongar e empurre de volta.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0251-9WTm7dq.gif',
  },
  {
    id: 'hanging-leg-raise-i3tscnc',
    name: 'Elevação de Pernas na Barra',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'bodyweight',
    instructions: 'Pendure-se na barra com braços estendidos e corpo estabilizado. Eleve as pernas estendidas até a altura do quadril contraindo o abdômen e desça sem balançar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0472-I3tsCnC.gif',
  },
  {
    id: 'inverted-row',
    name: 'Remada Invertida',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    instructions: 'Deite sob uma barra na altura da cintura, corpo reto e pegada pronada aberta. Puxe o peito até a barra juntando as escápulas e desça controlando até estender.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0499-bZGHsAZ.gif',
  },
  {
    id: 'crunch-floor',
    name: 'Abdominal Supra no Solo',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'bodyweight',
    instructions: 'Deite de costas com joelhos flexionados e pés no chão, mãos na nuca. Contraia o abdômen e eleve o tronco em direção aos joelhos; desça devagar sem puxar o pescoço.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0274-TFqbd8t.gif',
  },
  {
    id: 'reverse-crunch',
    name: 'Abdominal Infra no Solo',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'bodyweight',
    instructions: 'Deite de costas com os braços ao lado do corpo e joelhos flexionados a 90 graus. Contraia o abdômen e leve os joelhos ao peito tirando o quadril do chão; desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0872-nCU1Ekp.gif',
  },
  {
    id: 'russian-twist',
    name: 'Abdominal Russo',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'bodyweight',
    instructions: 'Sente no chão com joelhos flexionados e incline o tronco para trás. Mantenha o abdômen contraído e gire o tronco de um lado ao outro com as mãos unidas à frente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0687-XVDdcoj.gif',
  },
  {
    id: 'mountain-climber',
    name: 'Escalador',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['abs', 'shoulders', 'triceps'],
    equipment: 'bodyweight',
    instructions: 'Fique em prancha alta com as mãos sob os ombros e o corpo alinhado. Traga os joelhos ao peito alternadamente, em ritmo de corrida, mantendo o quadril baixo e o core firme.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0630-RJgzwny.gif',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'calves', 'shoulders'],
    equipment: 'bodyweight',
    instructions: 'Em pé, agache e apoie as mãos no chão. Jogue os pés para trás até a posição de flexão, retorne ao agachamento e finalize com um salto vertical com os braços estendidos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1160-dK9394r.gif',
  },
  {
    id: 'decline-sit-up',
    name: 'Abdominal Supra no Banco Declinado',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps', 'back'],
    equipment: 'bodyweight',
    instructions: 'Deite no banco declinado com os pés presos e os joelhos flexionados. Com as mãos na nuca ou no peito, suba o tronco enrolando a coluna e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0282-QLL2gdc.gif',
  },
  {
    id: '3-4-sit-up',
    name: 'Abdominal 3/4',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps', 'back'],
    equipment: 'bodyweight',
    instructions: 'Deite de costas com joelhos flexionados e pés no chão. Com as mãos na nuca, suba o tronco até cerca de 45 graus, contraindo o abdômen, e desça sem relaxar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0001-2gPfomN.gif',
  },
  {
    id: 'jump-squat',
    name: 'Agachamento com Salto',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'bodyweight',
    instructions: 'Com os pés na largura dos ombros, agache empurrando o quadril para trás. Salte explosivamente estendendo quadris, joelhos e tornozelos, e amorteça a aterrissagem.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0514-LIlE5Tn.gif',
  },
  {
    id: 'one-leg-squat',
    name: 'Agachamento Unilateral',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'bodyweight',
    instructions: 'Em pé, estenda uma perna à frente sem tocar o chão. Flexione o joelho de apoio descendo o quadril para trás, mantenha o tronco ereto e suba empurrando o calcanhar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1476-C31LMnP.gif',
  },
  {
    id: 'glute-ham-raise',
    name: 'Flexora Nórdica na Máquina',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'bodyweight',
    instructions: 'Posicione-se de bruços no aparelho com os tornozelos presos e os braços cruzados no peito. Desça o tronco controlando com os posteriores e suba contraindo glúteos e isquiotibiais.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3193-Vvwjz6N.gif',
  },
  {
    id: 'hyperextension',
    name: 'Hiperextensão Lombar',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    instructions: 'Ajuste o banco com as coxas apoiadas e os pés presos. Com os braços cruzados no peito, desça o tronco mantendo a coluna neutra e suba até o alinhamento do corpo.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0489-zhMwOwE.gif',
  },
  {
    id: 'donkey-calf-raise',
    name: 'Panturrilha Donkey',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'bodyweight',
    instructions: 'Apoie as pontas dos pés em um степ e as mãos em um suporte firme, quadril flexionado. Eleve os calcanhares ao máximo, contraia a panturrilha e desça alongando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0284-u5ESqzH.gif',
  },
  {
    id: 'decline-push-up',
    name: 'Flexão de Braço Declinada',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    instructions: 'Apoie as mãos no chão pouco além da largura dos ombros e os pés elevados em um banco. Desça o peito flexionando os cotovelos e empurre o chão mantendo o corpo alinhado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0279-i5cEhka.gif',
  },
  {
    id: 'jackknife-sit-up',
    name: 'Abdominal Canivete',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'bodyweight',
    instructions: 'Deite de costas com pernas estendidas e braços acima da cabeça. Suba pernas e tronco ao mesmo tempo levando as mãos aos pés, pause e desça de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0507-mbkgB44.gif',
  },
  {
    id: 'curl-up',
    name: 'Abdominal Curto',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'bodyweight',
    instructions: 'Deite de costas com joelhos flexionados e pés no chão. Com as mãos na nuca e cotovelos abertos, enrole a coluna elevando o tronco e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3016-g2oKspu.gif',
  },
  {
    id: 'split-squats',
    name: 'Agachamento Búlgaro Livre',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'bodyweight',
    instructions: 'Dê um passo à frente afastando bem as pernas. Desça flexionando os dois joelhos até o joelho de trás quase tocar o chão e suba empurrando o calcanhar da frente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2368-9E25EOx.gif',
  },
  {
    id: 'cable-shrug',
    name: 'Encolhimento no Cabo',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    instructions: 'De frente para a polia baixa, segure a barra com pegada pronada e braços estendidos. Eleve os ombros em direção às orelhas, contraia o trapézio e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0220-Eg98Ft9.gif',
  },
  {
    id: 'cable-upper-row',
    name: 'Remada Alta na Polia',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'cable',
    instructions: 'Prenda a barra reta na polia na altura do peito e segure com pegada pronada. Puxe a barra em direção ao tronco elevando os cotovelos e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1324-PQStVXH.gif',
  },
  {
    id: 'cable-rear-pulldown',
    name: 'Puxada por Trás na Polia',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    instructions: 'Sente no aparelho com os joelhos presos e segure a barra em pegada pronada aberta. Puxe a barra atrás da nuca aproximando as escápulas e retorne com controle.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0205-SpsOSXk.gif',
  },
  {
    id: 'one-leg-donkey-calf-raise',
    name: 'Panturrilha Donkey Unilateral',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'bodyweight',
    instructions: 'Apoie as mãos em um suporte firme e mantenha uma perna suspensa. Eleve o calcanhar da perna de apoio ao máximo, contraia a panturrilha e desça alongando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1386-A2upspL.gif',
  },
  {
    id: 'weighted-donkey-calf-raise',
    name: 'Panturrilha Donkey com Carga',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'bodyweight',
    instructions: 'Apoie as pontas dos pés na borda de um step e incline o tronco à frente segurando um apoio. Eleve os calcanhares ao máximo e desça controlando o alongamento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0833-LmaFNZS.gif',
  },
  {
    id: 'lever-seated-fly',
    name: 'Voador Máquina',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'back'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas no encosto e segure as pegadas com os cotovelos levemente flexionados. Feche os braços à frente do peito e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0596-v3xmPAR.gif',
  },
  {
    id: 'lever-chest-press-t0ytjgw',
    name: 'Supino Reto Máquina',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    instructions: 'Sente com as costas totalmente apoiadas e segure as pegadas na linha do peito. Empurre até estender os braços, expirando, e retorne devagar sem bater os pesos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0577-T0yTjgW.gif',
  },
  {
    id: 'lever-decline-chest-press',
    name: 'Supino Declinado Máquina',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    instructions: 'Ajuste o banco e o encosto, sente firme com os pés no chão e pegue as barras um pouco mais abertas que os ombros. Empurre à frente e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1300-vsVoPHt.gif',
  },
  {
    id: 'assisted-sit-up',
    name: 'Abdominal Supra com Apoio',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'machine',
    instructions: 'Deite com os joelhos flexionados e os pés fixos no apoio ou segurados por um parceiro. Mãos na nuca, suba o tronco contraindo o abdômen e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1758-aumB2IV.gif',
  },
  {
    id: 'assisted-hanging-knee-raise',
    name: 'Elevação de Joelhos Assistida',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['quadriceps'],
    equipment: 'machine',
    instructions: 'Apoie-se na máquina assistida com o corpo suspenso e o core contraído. Eleve os joelhos em direção ao peito, segure a contração e desça sem balançar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0011-03lzqwk.gif',
  },
  {
    id: 'smith-toe-raise',
    name: 'Panturrilha em Pé no Smith',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'machine',
    instructions: 'Ajuste a barra do Smith sobre os trapézios e apoie as pontas dos pés em um step. Eleve os calcanhares ao máximo e desça alongando a panturrilha.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1396-Y4QlY8z.gif',
  },
  {
    id: 'lever-deadlift',
    name: 'Levantamento Terra Máquina',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps'],
    equipment: 'machine',
    instructions: 'Ajuste o assento e a plataforma, apoie as costas e segure as pegadas. Estenda quadril e joelhos empurrando o chão e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0578-GUT8I22.gif',
  },
  {
    id: 'lever-shrug',
    name: 'Encolhimento Máquina',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas e segure as pegadas com os braços estendidos. Eleve os ombros em direção às orelhas, segure 1 segundo e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0604-ZZKbeMw.gif',
  },
  {
    id: 'lever-kneeling-leg-curl',
    name: 'Mesa Flexora Ajoelhado',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    instructions: 'Ajuste a máquina, ajoelhe com o tornozelo sob o rolo e segure as pegadas. Flexione o joelho levando o calcanhar ao glúteo e volte controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0582-nnmCTLN.gif',
  },
  {
    id: 'lever-seated-hip-adduction',
    name: 'Cadeira Adutora',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'machine',
    instructions: 'Sente com as costas apoiadas, pernas afastadas nos apoios e segure as pegadas. Junte as coxas contraindo os adutores e retorne devagar controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0598-oHsrypV.gif',
  },
  {
    id: 'smith-single-leg-split-squat',
    name: 'Agachamento Búlgaro no Smith',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    instructions: 'Fique sob a barra do Smith e apoie o pé de trás em um banco. Desça flexionando o joelho da frente até 90 graus e suba empurrando o calcanhar da frente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0768-wWFspEi.gif',
  },
  {
    id: 'lever-overhand-triceps-dip',
    name: 'Tríceps Mergulho Máquina',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'machine',
    instructions: 'Ajuste a máquina e segure as pegadas com pegada pronada e braços estendidos. Flexione os cotovelos junto ao corpo e estenda os braços contraindo o tríceps.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0591-D5yqP2p.gif',
  },
  {
    id: 'barbell-curl',
    name: 'Rosca Direta com Barra',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    instructions: 'Em pé, pés na largura dos ombros, segure a barra com pegada supinada. Com os cotovelos junto ao tronco, flexione até a altura dos ombros e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0031-25GPyDY.gif',
  },
  {
    id: 'barbell-drag-curl',
    name: 'Rosca Arrastada com Barra',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    instructions: 'Segure a barra com pegada supinada à frente das coxas. Suba a barra rente ao corpo levando os cotovelos para trás e desça controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0038-IENzBdA.gif',
  },
  {
    id: 'barbell-reverse-curl',
    name: 'Rosca Inversa com Barra',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    instructions: 'Em pé, segure a barra com pegada pronada e cotovelos junto ao tronco. Flexione até a altura dos ombros contraindo antebraços e bíceps e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0080-xNrS20v.gif',
  },
  {
    id: 'barbell-wide-squat',
    name: 'Agachamento Sumô com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Apoie a barra no trapézio com os pés mais afastados que os ombros e pontas viradas para fora. Desça empurrando o quadril para trás, mantendo o peito aberto, e suba pelos calcanhares.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0124-s7HX1BY.gif',
  },
  {
    id: 'barbell-bench-squat',
    name: 'Agachamento no Banco com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Com a barra apoiada no trapézio, posicione-se à frente do banco. Desça controlado até tocar levemente o banco com o glúteo, mantendo o tronco ereto, e suba estendendo quadril e joelhos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0026-W9pFVv1.gif',
  },
  {
    id: 'barbell-one-leg-squat',
    name: 'Agachamento Unilateral com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Apoie a barra no trapézio e estenda uma perna à frente, sem tocar o chão. Agache com a perna de apoio como se sentasse numa cadeira e retorne mantendo o tronco ereto.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0068-uKyN64F.gif',
  },
  {
    id: 'barbell-overhead-squat',
    name: 'Agachamento Overhead com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Segure a barra com pegada aberta e braços estendidos acima da cabeça. Agache mantendo a barra alinhada com o meio do pé, peito aberto e joelhos acompanhando a ponta dos pés.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0069-gfk9kD4.gif',
  },
  {
    id: 'barbell-clean-and-press',
    name: 'Arranco e Desenvolvimento com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['hamstrings', 'glutes', 'shoulders'],
    equipment: 'barbell',
    instructions: 'Com pegada pronada e barra no chão, estenda quadril e joelhos puxando a barra rente ao corpo até os ombros. Em seguida, empurre a barra acima da cabeça e retorne controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0028-SGY8Zui.gif',
  },
  {
    id: 'barbell-decline-pullover',
    name: 'Pullover Declinado com Barra',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    instructions: 'Deitado no banco declinado com os pés presos, segure a barra em pegada pronada com os braços semiestendidos sobre o peito. Leve a barra para trás da cabeça e retorne contraindo o peitoral.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1255-9sgNE2O.gif',
  },
  {
    id: 'barbell-wide-bench-press',
    name: 'Supino Reto Pegada Aberta',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    instructions: 'Deitado no banco reto, segure a barra com pegada bem aberta. Desça a barra até a linha do peito de forma controlada e empurre até a extensão completa dos cotovelos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0122-JsKq9so.gif',
  },
  {
    id: 'barbell-pullover',
    name: 'Pullover com Barra',
    primaryMuscles: ['back'],
    secondaryMuscles: ['chest', 'triceps'],
    equipment: 'barbell',
    instructions: 'Deitado no banco reto, segure a barra na largura dos ombros com os braços estendidos sobre o peito. Leve a barra para trás da cabeça até sentir o alongamento do dorsal e retorne.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0073-i6LWjok.gif',
  },
  {
    id: 'barbell-incline-row',
    name: 'Remada Curvada no Banco Inclinado',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'barbell',
    instructions: 'Deite de peito no banco inclinado a 45 graus e segure a barra em pegada pronada. Puxe a barra até o abdômen, juntando as escápulas, e desça controlado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0049-dmgMp3n.gif',
  },
  {
    id: 'barbell-pendlay-row',
    name: 'Remada Pendlay',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'barbell',
    instructions: 'Com os pés na largura dos ombros, incline o tronco até quase paralelo ao chão mantendo a coluna neutra. Puxe a barra do chão até o abdômen e retorne apoiando-a no solo a cada repetição.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3017-r0z6xzQ.gif',
  },
  {
    id: 'barbell-lunge',
    name: 'Avanço com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Com a barra apoiada no trapézio, dê um passo à frente mantendo o tronco ereto. Flexione o joelho até a coxa ficar paralela ao chão e empurre o calcanhar para voltar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0054-t8iSghb.gif',
  },
  {
    id: 'barbell-step-up',
    name: 'Subida no Banco com Barra',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'barbell',
    instructions: 'Com a barra no trapézio, apoie todo o pé sobre o banco. Empurre pelo calcanhar até estender quadril e joelho no topo e desça controlado com a outra perna.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0114-Kxquu2E.gif',
  },
  {
    id: 'barbell-seated-calf-raise',
    name: 'Panturrilha Sentado com Barra',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'quadriceps'],
    equipment: 'barbell',
    instructions: 'Sentado no banco, apoie a barra sobre as coxas e as pontas dos pés em um step. Eleve os calcanhares ao máximo, segure a contração e desça alongando a panturrilha.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0088-ktsFQAZ.gif',
  },
  {
    id: 'barbell-standing-calf-raise',
    name: 'Panturrilha em Pé com Barra',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    instructions: 'Em pé com a barra apoiada no trapézio e pés na largura dos ombros, eleve os calcanhares ao máximo. Segure a contração no topo e desça devagar até a posição inicial.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1372-8ozhUIZ.gif',
  },
  {
    id: 'barbell-thruster',
    name: 'Thruster com Barra',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'barbell',
    instructions: 'Segure a barra na altura dos ombros, agache até a coxa paralela e, ao subir, estenda os quadris explosivamente empurrando a barra acima da cabeça.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3305-f7Y9eDZ.gif',
  },
  {
    id: 'barbell-front-raise',
    name: 'Elevação Frontal com Barra',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['biceps', 'triceps'],
    equipment: 'barbell',
    instructions: 'Em pé, segure a barra à frente das coxas com pegada pronada. Eleve os braços estendidos até a altura dos ombros e desça controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0041-b2Uoz54.gif',
  },
  {
    id: 'barbell-upright-row',
    name: 'Remada Alta com Barra',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'biceps'],
    equipment: 'barbell',
    instructions: 'Com pegada pronada pouco mais aberta que os ombros, puxe a barra rente ao corpo até o queixo liderando com os cotovelos. Desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0120-UDlhcO8.gif',
  },
  {
    id: 'barbell-one-arm-snatch',
    name: 'Arranco Unilateral com Barra',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['back', 'forearms', 'abs'],
    equipment: 'barbell',
    instructions: 'Pés na largura dos ombros e quadril baixo, segure a barra com uma mão. Estenda pernas e quadril explosivamente e receba a barra acima da cabeça com o braço travado.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0067-xHKN2s8.gif',
  },
  {
    id: 'barbell-good-morning',
    name: 'Bom Dia com Barra',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['back'],
    equipment: 'barbell',
    instructions: 'Com a barra no trapézio e joelhos levemente flexionados, empurre o quadril para trás até o tronco ficar quase paralelo ao chão. Volte contraindo glúteos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0044-XlZ4lAC.gif',
  },
  {
    id: 'barbell-straight-leg-deadlift',
    name: 'Levantamento Terra Pernas Estendidas',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    instructions: 'Segure a barra com pegada pronada e joelhos quase estendidos. Desça a barra rente às pernas flexionando o quadril e suba contraindo posteriores e glúteos.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0116-hrVQWvE.gif',
  },
  {
    id: 'power-clean',
    name: 'Power Clean',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'quadriceps', 'calves'],
    equipment: 'barbell',
    instructions: 'Com a barra no chão e pegada pronada, mantenha a coluna neutra e puxe a barra rente ao corpo, estendendo quadris e joelhos para recebê-la nos ombros.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0648-SiWCcTN.gif',
  },
  {
    id: 'barbell-press-sit-up',
    name: 'Abdominal com Barra no Peito',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'chest'],
    equipment: 'barbell',
    instructions: 'Deitado com joelhos flexionados, apoie a barra no peito. Contraia o abdômen e eleve o tronco até cerca de 45 graus, descendo de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0071-wnEscH8.gif',
  },
  {
    id: 'barbell-seated-twist',
    name: 'Rotação de Tronco Sentado com Barra',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'back'],
    equipment: 'barbell',
    instructions: 'Sentado no banco, segure a barra à frente do peito. Com a coluna ereta e o core ativo, gire o tronco para um lado e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0094-dFSNDOA.gif',
  },
  {
    id: 'barbell-standing-twist',
    name: 'Rotação de Tronco em Pé com Barra',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'back'],
    equipment: 'barbell',
    instructions: 'Em pé, segure a barra à frente do peito com o core ativo. Gire o tronco para um lado mantendo o quadril estável e alterne os lados de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0112-yQe5HpE.gif',
  },
  {
    id: 'barbell-reverse-wrist-curl',
    name: 'Rosca Inversa de Punho com Barra',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    instructions: 'Sentado, apoie os antebraços nas coxas com pegada pronada e punhos livres. Estenda os punhos elevando a barra e retorne lentamente à posição inicial.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0082-LsZkfU6.gif',
  },
  {
    id: 'cable-front-raise',
    name: 'Elevação Frontal na Polia',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'forearms'],
    equipment: 'cable',
    instructions: 'De costas para a polia baixa, segure a barra ou o puxador com pegada pronada. Eleve os braços estendidos até a altura dos ombros e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0162-u2X71Np.gif',
  },
  {
    id: 'cable-forward-raise',
    name: 'Elevação Frontal Bilateral na Polia',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'forearms'],
    equipment: 'cable',
    instructions: 'Em pé com joelhos semiflexionados, segure o puxador com as palmas para baixo. Suba os braços estendidos até a altura dos ombros e desça de forma controlada.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0161-hvHhCv8.gif',
  },
  {
    id: 'cable-pushdown',
    name: 'Tríceps Pulley',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'De frente para a polia alta, segure a barra com pegada pronada e cotovelos junto ao tronco. Estenda os cotovelos até travar e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0201-3ZflifB.gif',
  },
  {
    id: 'cable-reverse-grip-pushdown',
    name: 'Tríceps Pulley Pegada Inversa',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Na polia alta, segure a barra com pegada supinada e cotovelos fixos ao lado do corpo. Estenda os cotovelos totalmente e volte controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0207-VjYliFZ.gif',
  },
  {
    id: 'cable-one-arm-tricep-pushdown',
    name: 'Tríceps Pulley Unilateral',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Fique de frente ao pulley alto, segure o punho com uma mão e cotovelo colado ao corpo. Estenda o antebraço até travar e retorne controlando o movimento.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1723-qRZ5S1N.gif',
  },
  {
    id: 'cable-low-fly',
    name: 'Crucifixo Inverso na Polia Baixa',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Com as polias baixas, fique no centro da máquina, braços levemente flexionados. Suba as mãos à frente até a altura dos ombros, contraia o peitoral e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0179-FVmZVhk.gif',
  },
  {
    id: 'cable-lying-fly',
    name: 'Crucifixo na Polia Deitado',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Deite no banco entre as polias com os braços estendidos acima do peito. Abra os braços em arco até sentir o alongamento do peitoral e volte contraindo.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0185-lJJ7Yq8.gif',
  },
  {
    id: 'cable-middle-fly',
    name: 'Crucifixo na Polia Média',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Com as polias na altura do peito, fique no centro com um pé à frente. Una as mãos à frente do peito em arco, contraia o peitoral e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0188-xLYSdtg.gif',
  },
  {
    id: 'cable-bench-press',
    name: 'Supino na Polia em Pé',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'cable',
    instructions: 'De costas para a máquina, com as polias na altura do peito, segure os punhos em pronação. Empurre os braços à frente até estender e volte devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0151-7xI5MXA.gif',
  },
  {
    id: 'cable-decline-fly',
    name: 'Crucifixo Declinado na Polia',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'cable',
    instructions: 'Com as polias altas, fique de costas para a máquina e braços abertos. Una as mãos para baixo e à frente do quadril, contraindo o peitoral inferior, e retorne.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0158-7saC5zz.gif',
  },
  {
    id: 'cable-curl',
    name: 'Rosca Direta na Polia',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'De frente para a polia baixa, segure a barra em supinação com os cotovelos junto ao tronco. Flexione os cotovelos até os ombros e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0868-G08RZcQ.gif',
  },
  {
    id: 'cable-drag-curl',
    name: 'Rosca Arrastada na Polia',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Segure a barra em supinação na polia baixa e puxe os cotovelos para trás, arrastando a barra rente ao tronco. Contraia o bíceps no topo e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1632-dXz8zjF.gif',
  },
  {
    id: 'cable-seated-curl',
    name: 'Rosca na Polia Sentado',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    instructions: 'Sentado de frente para a polia baixa, segure o punho em supinação com braços estendidos. Flexione os cotovelos mantendo os braços parados e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1641-8oYqOt9.gif',
  },
  {
    id: 'cable-deadlift',
    name: 'Levantamento Terra na Polia',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps', 'back'],
    equipment: 'cable',
    instructions: 'De frente para a polia baixa, flexione quadril e joelhos mantendo a coluna neutra. Suba estendendo quadril e joelhos, contraindo os glúteos no final.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0157-eGDudUV.gif',
  },
  {
    id: 'cable-standing-hip-extension',
    name: 'Extensão de Quadril na Polia',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps'],
    equipment: 'cable',
    instructions: 'Com a caneleira no tornozelo e de frente para a polia baixa, apoie as mãos na máquina. Leve a perna para trás contraindo o glúteo e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0228-Kpajagk.gif',
  },
  {
    id: 'cable-hip-adduction',
    name: 'Adução de Quadril na Polia',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    equipment: 'cable',
    instructions: 'Prenda a caneleira no tornozelo e fique de lado para a polia baixa. Leve a perna cruzando à frente da linha do corpo e retorne controlando a tensão.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0168-hBGWILP.gif',
  },
  {
    id: 'cable-twist',
    name: 'Rotação de Tronco na Polia',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'cable',
    instructions: 'Em pé, de lado para a polia na altura do peito, segure o punho com as duas mãos. Gire o tronco puxando o cabo, contraia o abdômen e volte devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0243-aVs3BR3.gif',
  },
  {
    id: 'cable-seated-twist',
    name: 'Rotação de Tronco Sentado na Polia',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: 'cable',
    instructions: 'Sentado com os braços estendidos à frente, segure o punho com as duas mãos. Gire o tronco para o lado mantendo o abdômen firme e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2399-UEjSrKI.gif',
  },
  {
    id: 'cable-wrist-curl',
    name: 'Rosca de Punho na Polia',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    instructions: 'Com a barra na polia baixa em supinação, apoie os antebraços nas coxas. Flexione os punhos para cima contraindo os antebraços e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0247-LrV4s90.gif',
  },
  {
    id: 'cable-reverse-wrist-curl',
    name: 'Rosca Inversa de Punho na Polia',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: 'cable',
    instructions: 'Sentado, segure a barra da polia baixa em pronação com os antebraços apoiados nas coxas. Estenda os punhos para cima e retorne com controle.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0210-eYmsEPR.gif',
  },
  {
    id: 'cable-standing-calf-raise',
    name: 'Panturrilha em Pé na Polia',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'cable',
    instructions: 'Em pé de frente para a polia, segure os punhos e mantenha o tronco ereto. Suba nas pontas dos pés ao máximo, segure a contração e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1375-yl2IYyy.gif',
  },
  {
    id: 'cable-standing-one-leg-calf-raise',
    name: 'Panturrilha Unilateral na Polia',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'cable',
    instructions: 'Apoie-se na máquina e sustente o corpo em uma perna só. Eleve o calcanhar ao máximo, contraia a panturrilha e desça controlando a descida.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1376-fgc9Xdl.gif',
  },
  {
    id: 'dumbbell-decline-fly',
    name: 'Crucifixo Declinado com Halteres',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deite no banco declinado com os halteres acima do peito e palmas frente a frente. Abra os braços em arco até sentir o alongamento do peitoral e retorne contraindo.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0302-xXm4nYq.gif',
  },
  {
    id: 'dumbbell-incline-fly',
    name: 'Crucifixo Inclinado com Halteres',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Ajuste o banco a 45 graus e deite com os halteres estendidos acima do peito. Abra os braços em arco, com leve flexão de cotovelos, e retorne contraindo o peitoral.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0319-ESOd5Pl.gif',
  },
  {
    id: 'dumbbell-high-curl',
    name: 'Rosca Alta com Halteres',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    instructions: 'Em pé, segure os halteres com as palmas à frente. Mantenha os braços fixos e flexione os cotovelos o mais alto possível, contraia no topo e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1664-qAmNMJY.gif',
  },
  {
    id: 'dumbbell-biceps-curl',
    name: 'Rosca Direta com Halteres',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    instructions: 'Em pé, braços estendidos e palmas à frente. Mantendo os cotovelos junto ao tronco, suba os halteres até a altura dos ombros e retorne controlando a descida.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0294-NbVPDMW.gif',
  },
  {
    id: 'dumbbell-seated-curl',
    name: 'Rosca Direta Sentado com Halteres',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    instructions: 'Sente no banco com os pés apoiados e as palmas à frente. Com as costas retas e cotovelos colados ao tronco, flexione os halteres até os ombros e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0391-TiaZTxx.gif',
  },
  {
    id: 'dumbbell-push-press',
    name: 'Desenvolvimento com Impulso (Halteres)',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: 'dumbbell',
    instructions: 'Em pé, halteres na altura dos ombros. Flexione levemente os joelhos e, de forma explosiva, estenda as pernas empurrando os halteres acima da cabeça. Desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1700-FS63wTN.gif',
  },
  {
    id: 'dumbbell-clean',
    name: 'Clean com Halteres',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quadriceps', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Com os halteres ao lado do corpo, agache com costas retas e peito aberto. Estenda quadris e joelhos de forma explosiva e puxe os halteres até a altura dos ombros.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0295-7Hg55JG.gif',
  },
  {
    id: 'dumbbell-squat',
    name: 'Agachamento com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Em pé, halteres ao lado do corpo, peito aberto e abdômen contraído. Desça flexionando joelhos e quadris até as coxas ficarem paralelas ao chão e suba pelos calcanhares.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0413-HsvHqgf.gif',
  },
  {
    id: 'dumbbell-incline-row',
    name: 'Remada Inclinada com Halteres',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deite com o peito apoiado no banco inclinado a 45 graus e deixe os halteres pendurados. Puxe os cotovelos para trás, aproximando as escápulas, e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0327-7vG5o25.gif',
  },
  {
    id: 'dumbbell-decline-shrug',
    name: 'Encolhimento Declinado com Halteres',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deite de peito no banco declinado com os halteres pendurados em direção ao chão. Sem dobrar os cotovelos, eleve os ombros contraindo o trapézio e retorne devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0305-cwsAI4G.gif',
  },
  {
    id: 'dumbbell-incline-shrug',
    name: 'Encolhimento Inclinado com Halteres',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Sente no banco inclinado a 45 graus com os halteres pendurados e palmas para o corpo. Com os braços estendidos, eleve os ombros em direção às orelhas e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0329-JymLInS.gif',
  },
  {
    id: 'dumbbell-step-up-lunge',
    name: 'Avanço no Step com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Em pé de frente ao step, halteres ao lado do corpo. Apoie todo o pé direito no step, empurre pelo calcanhar para subir e desça controlando. Alterne as pernas.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2796-gFyFj9z.gif',
  },
  {
    id: 'dumbbell-supported-squat',
    name: 'Agachamento Apoiado com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Em pé, halteres ao lado do corpo, peito aberto e core ativado. Desça devagar flexionando os joelhos e jogando o quadril para trás até as coxas paralelas; suba controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2803-r5DgrW9.gif',
  },
  {
    id: 'dumbbell-step-up-split-squat',
    name: 'Agachamento Unilateral no Step',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'De frente ao banco, halteres ao lado do corpo. Apoie todo o pé direito no banco e empurre pelo calcanhar para subir, mantendo o tronco ereto. Desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2812-QjE2DcA.gif',
  },
  {
    id: 'dumbbell-single-leg-split-squat',
    name: 'Agachamento Búlgaro com Halteres',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Com os halteres ao lado do corpo, apoie o pé de trás em um banco e o da frente firme no chão. Desça flexionando o joelho da frente e suba empurrando pelo calcanhar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0410-qx4fgX7.gif',
  },
  {
    id: 'dumbbell-kickback',
    name: 'Tríceps Coice com Halteres',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Em pé, inclinado à frente com as costas retas, mantenha os braços colados ao tronco e estenda os antebraços para trás até travar o tríceps. Retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0333-W6PxUkg.gif',
  },
  {
    id: 'dumbbell-seated-kickback',
    name: 'Tríceps Coice Sentado com Halteres',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    instructions: 'Sentado no banco, incline o tronco à frente com a coluna reta. Com os braços fixos ao lado do corpo, estenda os antebraços para trás e volte devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0394-en550rk.gif',
  },
  {
    id: 'dumbbell-close-grip-press',
    name: 'Supino Fechado com Halteres',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'dumbbell',
    instructions: 'Deitado no banco reto, una os halteres sobre o peito com as palmas à frente. Empurre para cima mantendo os cotovelos próximos ao corpo e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1731-7jGOBF3.gif',
  },
  {
    id: 'dumbbell-one-arm-wrist-curl',
    name: 'Rosca de Punho Unilateral com Halter',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    instructions: 'Sentado, apoie o antebraço na coxa com a palma para cima segurando o halter. Deixe o punho estender e flexione-o para cima, contraindo o antebraço.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0364-q8aHNoF.gif',
  },
  {
    id: 'dumbbell-reverse-wrist-curl',
    name: 'Rosca Inversa de Punho com Halteres',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    instructions: 'Sentado, apoie os antebraços nas coxas com as palmas para baixo e os punhos livres. Estenda os punhos para cima e retorne devagar sem mover os antebraços.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0385-BLCvwr2.gif',
  },
  {
    id: 'kettlebell-hang-clean',
    name: 'Clean Suspenso com Kettlebell',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'quadriceps', 'calves'],
    equipment: 'dumbbell',
    instructions: 'Em pé, segure o kettlebell à frente das coxas. Flexione os joelhos e quadris com a coluna reta, balance o peso entre as pernas e puxe-o explosivamente até a altura do ombro.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0535-LHWF7us.gif',
  },
  {
    id: 'dumbbell-standing-calf-raise',
    name: 'Panturrilha em Pé com Halteres',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    instructions: 'Em pé, com um halter em cada mão, eleve os calcanhares o máximo possível contraindo as panturrilhas. Pause no topo e desça lentamente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0417-dPmaUaU.gif',
  },
  {
    id: 'dumbbell-single-leg-calf-raise',
    name: 'Panturrilha Unilateral com Halter',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: 'dumbbell',
    instructions: 'Apoie a ponta do pé na borda do step, segure um halter e firme-se com a outra mão. Eleve o calcanhar ao máximo, pause e desça alongando a panturrilha.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0409-1kB3Wmk.gif',
  },
  {
    id: 'standing-single-leg-curl',
    name: 'Flexão de Joelho em Pé',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    equipment: 'bodyweight',
    instructions: 'Em pé, com as mãos na cintura, apoie o peso em uma perna. Flexione o joelho da outra levando o calcanhar ao glúteo e contraia o posterior. Retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0795-C5jncD2.gif',
  },
  {
    id: 'inverse-leg-curl-bench-support',
    name: 'Flexora Inversa no Banco',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'bodyweight',
    instructions: 'Deitado de bruços no banco com o quadril na borda e pernas estendidas, segure firme. Flexione os joelhos levando os calcanhares aos glúteos e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0496-ms7tjSG.gif',
  },
  {
    id: 'lower-back-curl',
    name: 'Extensão Lombar no Solo',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    instructions: 'Deitado de bruços com os braços ao lado do corpo, contraia glúteos e posteriores e eleve o tronco do chão. Pause no topo e desça lentamente.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1352-ANbbry2.gif',
  },
  {
    id: 'weighted-front-raise',
    name: 'Elevação Frontal com Peso',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    instructions: 'Em pé, segure os pesos com as palmas voltadas para as coxas. Com os braços estendidos, eleve até a altura dos ombros, pause e desça controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0834-e4aFmFY.gif',
  },
  {
    id: 'smith-machine-bicep-curl',
    name: 'Rosca Direta no Smith',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'machine',
    instructions: 'Ajuste a barra do Smith na altura da cintura e pegue em supinação com as mãos pouco além dos ombros. Flexione os cotovelos até o topo e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1683-zILLZ98.gif',
  },
  {
    id: 'lever-reverse-grip-preacher-curl',
    name: 'Rosca Scott Pegada Inversa na Máquina',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: 'machine',
    instructions: 'Ajuste o assento e apoie os braços no banco Scott. Segure as pegadas em pronação, flexione os cotovelos até a contração máxima e retorne controlando.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1616-kj3hy6W.gif',
  },
  {
    id: 'smith-seated-wrist-curl',
    name: 'Rosca de Punho Sentado no Smith',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    instructions: 'Sentado de frente para o Smith, segure a barra em supinação com as mãos na largura dos ombros e antebraços nas coxas. Flexione os punhos para cima e desça devagar.',
    gifUrl: 'https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1426-B6dAO1t.gif',
  },
];
